/**
 * Industry/type classification for entities, derived from each filer's own
 * reported occupation (state-filed, self-reported) and — for a curated set of
 * well-known organizations where that self-report is generic or misleading —
 * real-world identity. Generated from the manual classification pass reviewed
 * against `william-s-jones-origins` (2,700+ rows, ~230 at $20k+ hand-checked
 * individually, the rest via this same rule set). Do not hand-edit the three
 * data tables below; regenerate them if the taxonomy changes.
 */

/**
 * Specific entities whose filed occupation would mislabel them — a homebuilder
 * self-reporting "REAL ESTATE COMPANY", a lobbying firm self-reporting
 * "POLITICAL COMMITTEE". Keyed on the entity's exact display name, checked
 * before the occupation map so it always wins.
 */
export const NAME_OVERRIDES: Record<string, string> = {
  "21st Century Public Servant": "Political committee",
  "360 GLOBAL SOLUTIONS LLC": "Investments",
  "A. DUDA AND SONS, INC.": "Agriculture",
  "ABC LIQUORS, INC.": "Alcohol",
  "ABRAHAMSON & UITERWYK": "Law firm",
  "AIRBNB, INC.": "Short-term rentals",
  "ALAMO GROUP HOLDINGS LLC": "Manufacturing",
  "ALLEN RONALD J": "Real estate",
  "ALTRIA CLIENT SERVICES, LLC": "Tobacco",
  "AMERICAN INTEGRITY MGA LLC": "Property insurance",
  "AMSCOT CORPORATION": "Financial services",
  "ARB INTERACTIVE": "Technology",
  "ARISTOTLE INTERNATIONAL INC.": "Political technology",
  "ASPIRE HEALTH GROUP": "Healthcare",
  "ASSOCIATED INDUSTRIES OF FLORIDA PAC": "Trade association",
  "ASTON HEALTHCARE, LLC": "Healthcare",
  "American Values Fund": "Political committee",
  "Associated Industries of Florida Political Action Committee": "Trade association",
  "B R W CONTRACTING INC": "Construction",
  "BANK OF TAMPA MONEY MARKET ACCOUNT": "Banking",
  "BARBER & ASSOCIATES INC": "Roofing",
  "BASS UNDERWRITERS INC.": "Property insurance",
  "BIG CREEK TIMBER LLC": "Timber",
  "BLUE WATER INDUSTRIES FLORIDA LLC": "Construction",
  "BLUENEST DEVELOPMENT LLC": "Developer",
  "BOUWER MARILYN R": "Retired",
  "BRAMAN MANAGEMENT LLC": "Auto dealers",
  "BUSPATROL AMERICA, LLC": "Transportation safety",
  "CDR ENTERPRISES, INC": "Engineering",
  "CENTENE MANAGEMENT COMPANY LLC": "Health insurance",
  "CEOMC FLORIDA, INC.": "Property management",
  "CGL COMPANIES": "Corrections",
  "CHAN ANN": "Homemaker",
  "CHARTER COMMUNICATIONS": "Telecom",
  "CHRISTIAN FINANCIAL RESOURCES": "Financial services",
  "CHURCHILL DOWNS, INC.": "Horse racing",
  "CITIZENS ALLIANCE FOR FLORIDA' S ECONOMY": "Trade association",
  "CLEGG INSURANCE ADVISORS LLC": "Insurance",
  "COKER HOWARD C.": "Law firm",
  "COMCAST CORPORATION": "Telecom",
  "COMCAST FINANCIAL AGENCY CORPORATION": "Telecom",
  "CONSENSUS COMMUNICATIONS, INC.": "Public relations",
  "CONSORTIUM OF NORTH EAST FLORIDA BUSINESSES": "Trade association",
  "CORCORAN MICHAEL": "Lobbying",
  "DISNEY WORLDWIDE SERVICES": "Theme parks",
  "DOSAL TOBACCO CORP": "Tobacco",
  "DREAM FINDERS HOMES LLC": "Developer",
  "DUKE ENERGY": "Energy utility",
  "DUKE ENERGY FLORIDA, LLC": "Energy utility",
  "ECONOMIC IMPROVEMENT FUND, INC.": "Political committee",
  "EDGEWATER BEACH HOTEL": "Hotels",
  "EISENHOWER MANAGEMENT INC": "Property management",
  "ENSTRUCTURE": "Logistics",
  "ESTUARY LLC": "Real estate",
  "Edwards and Ragatz PA": "Law firm",
  "Excellent Public Schools PAC": "Education",
  "F. CAIN STEPHEN": "Law firm",
  "FANDUEL GROUP INC": "Sports betting",
  "FAPSC PAC": "For-profit education",
  "FARAH & FARAH ATTORNEYS AT LAW": "Law firm",
  "FCCI SERVICES, INC.": "Property insurance",
  "FERGUSON HOWELL": "Horse racing",
  "FERNWOOD MANAGEMENT": "Real estate",
  "FIDELITY INVESTMENTS": "Financial services",
  "FIGGERS COMMUNICATION, INC.": "Telecom",
  "FIRST COAST ENERGY, LLP": "Petroleum",
  "FIRSTSERVICE RESIDENTIAL FLORIDA, INC.": "Property management",
  "FISHER MARK": "Investments",
  "FL CHAMBER OF COMM PAC": "Trade association",
  "FLEETFORCE TRUCK DRIVING SCHOOL B-3-1, LLC": "Transportation safety",
  "FLORIDA BLUE": "Health insurance",
  "FLORIDA CRYSTALS CORPORATION": "Sugar",
  "FLORIDA HEALTHCARE MANAGEMENT, LLC": "Healthcare",
  "FLORIDA INSURANCE COUNCIL": "Trade association",
  "FLORIDA JUSTICE PC": "Political committee",
  "FLORIDA MEDICAL ASSOCIATION": "Trade association",
  "FLORIDA POWER & LIGHT COMPANY": "Energy utility",
  "Fairness in Taxation": "Political committee",
  "First Principles": "Political committee",
  "Florida CUPAC": "Credit unions",
  "Florida Campground Political Action Committee": "Campgrounds",
  "Florida Citrus Mutual Poltical Committee": "Citrus",
  "Florida Education Association Advocacy Fund": "Labor union",
  "Florida Future Fund": "Political committee",
  "Florida Police Benevolent Association Inc FPBA Law and Order PAC": "Law enforcement union",
  "Florida Republican Senatorial Campaign Committee, Inc.": "Political party",
  "Florida Thoroughbred Political Action Committee": "Horse racing",
  "Foundation for Florida's Future PAC": "Political committee",
  "Franklin, Gallop P. (DEM)(STR)": "Candidate committee",
  "Friends of Ben Albritton": "Candidate committee",
  "Friends of Danny Alvarez": "Candidate committee",
  "Friends of Jim Boyd": "Candidate committee",
  "GAF MATERIALS LLC": "Roofing",
  "GARCIA DEVELOPMENT COMPANY": "Developer",
  "GLK REAL ESTATE LLC": "Real estate",
  "GLOBAL KRATOM COALITION": "Kratom",
  "GOLDENFARB CRAIG M.": "Law firm",
  "GOLDMAN BABBONI FERNANDAZ  MURPHY & WALSH": "Law firm",
  "GOLIATH VENTURES INC": "Investments",
  "GORDON & PARTNERS, P.A.": "Law firm",
  "GROW FLORIDA": "Political committee",
  "GUIDEWELL GROUP, INC": "Health insurance",
  "GULFSTREAM PARK": "Horse racing",
  "GUSTAFSON JR JAMES W": "Law firm",
  "General Motors Company Political Action Committee (GM PAC)": "Automotive",
  "HASTINGS REED": "Streaming media",
  "HATZALAH": "Emergency medical services",
  "HCA NORTH FLORIDA DIVISION AND GOOD GOVERNMENT GROUP": "Healthcare",
  "HCA North Florida Division Good Government PAC": "Healthcare",
  "HCA West Florida Division Good Government PAC": "Healthcare",
  "HERITAGE MGA LLC": "Property insurance",
  "HOMES BY WEST BAY, LLC": "Developer",
  "ICI HOMES RESIDENTIAL HOLDINGS LLC": "Developer",
  "INTERNATIONAL ASSOCIATION OF FIREFIGHTERS": "Labor union",
  "INTERVEST CONSTRUCTION INDUSTRIES": "Construction",
  "J M FAMILY AUTOMOTIVE LLC": "Auto dealers",
  "J.B. Coxwell Contracting, Inc.": "Construction",
  "JACKSONVILLE JAGUARS, LLC": "Professional sports",
  "JACKSTONE DEVELOPMENT": "Developer",
  "JASON PIZZO CAMPAIGN": "Candidate committee",
  "JAX BIZ": "Trade association",
  "JWB REAL ESTATE CAPITAL LLC ALEX": "Real estate",
  "KAYLEE TUCK CAMPAIGN": "Candidate committee",
  "KEMP LAW": "Law firm",
  "KIRTLEY JOHN": "Investments",
  "KLEPACH BERNARD": "Logistics",
  "KOLTER PAYMENTS LLC": "Financial services",
  "LAND EXPERTS, INC.": "Real estate",
  "LANGLEY CONSULTING GROUP INC": "Consulting",
  "LEE FP INC.": "Healthcare",
  "LEMA CONSTRUCTION": "Construction",
  "LEO TECHNOLOGIES": "Technology",
  "LEWIS LONGMAN & WALKER P.A": "Law firm",
  "LIGORI & LIGORI P.A": "Law firm",
  "LIGORI CHRISTOPHER": "Law firm",
  "LTD. UNIVERSAL CITY DEVELOPMENT PARTNERS": "Theme parks",
  "LYFT": "Rideshare",
  "LYKES BROS., INC.": "Agriculture",
  "LYTAL, REITER, SMITH, IVEY & FRONRATH, LLP": "Law firm",
  "MANATEE COUNTY REC": "Political party",
  "MARATHON PETROLEUM CO LP": "Petroleum",
  "MASTEC": "Construction",
  "MAYFIELD DEBORAH J": "Candidate committee",
  "MCCOY VENTURES LLC": "Venture capital",
  "MCGUIREWOODS": "Law firm",
  "MICHLES & BOOTH P.A": "Law firm",
  "MOMENTUM TRANSPORTATION USA INC": "Trucking",
  "MORTON RICHARD ASHLEY": "Real estate",
  "MOSAIC GLOBAL SALES LLC": "Phosphate mining",
  "MOSS & ASSOCIATES, LLC": "Construction",
  "NEAL LAND & NEIGHBORHOODS, LLC": "Developer",
  "NECTRIS LLC": "Laboratory services",
  "NEUROSPINE PLUS LLC": "Healthcare",
  "NEXTERA ENERGY CAPITAL HOLDINGS INC": "Energy utility",
  "ORANGE BARREL MEDIA, LLC": "Advertising",
  "OUTPOST BRANDS, LLC": "Hemp products",
  "Orange Lake Resort Alliance": "Hospitality",
  "PARC Group": "Developer",
  "PCI GAMING AUTHORITY": "Gaming",
  "PETWAY IV THOMAS F": "Insurance",
  "PHILLIPS INFRASTRUCTURE CORP": "Construction",
  "PMI GLOBAL SERVICES INC.": "Tobacco",
  "PMI US CORPORATE SERVICES": "Tobacco",
  "PNC BANK NA": "Banking",
  "PROPEL FLORIDA LLC": "Technology",
  "RACETRAC PETROLEUM, INC.": "Petroleum",
  "RACETRAC, INC.": "Petroleum",
  "RAI SERVICES COMPANY": "Tobacco",
  "RAYS BASEBALL CLUB LLC": "Professional sports",
  "REASYN TECHNOLOGIES, INC.": "Technology",
  "RELIAQUEST, LLC": "Cybersecurity",
  "RENNERT VOGEL MANDLER & RODRIGUEZ PA": "Law firm",
  "REYNOLDS AMERICAN": "Tobacco",
  "RUBENSTEIN ROBERT M": "Law firm",
  "RYAN SPECIALTY LLC": "Insurance",
  "Republican Party of Florida": "Political party",
  "Republican State Leadership Committee": "Political committee",
  "S/R SERVICE & SUPPORT CORP": "Legal services",
  "SAFETY NET HOSPITAL ALLIANCE OF FLORIDA": "Healthcare",
  "SAFETY NET HOSPITAL ALLIANCE SERVICE CORPORATION": "Healthcare",
  "SCHOOL DEVELOPMENT HC FINANCE LLC": "Education",
  "SE ANDERSON ORANGE II LLC": "Real estate",
  "SHUMAKER ADVISORS FLORIDA LLC": "Lobbying",
  "SHUMAKER FLORIDA PC": "Law firm",
  "SIG SAUER, INC.": "Firearms",
  "SLIDE INSURANCE HOLDINGS INC": "Property insurance",
  "SOLARIS LICENSING, LLC": "Healthcare",
  "SOUTHERN GLAZER'S WINE AND SPIRITS": "Alcohol",
  "SPENCER ROBERT N.": "Law firm",
  "SPINE SPECIALISTS OF SOUTH FLORIDA LLC": "Healthcare",
  "STATEN ISLAND CARE CENTER": "Nursing homes",
  "STRATEGIC DIGITAL SERVICES LLC": "Digital media",
  "SUDDATH STEPHEN": "Logistics",
  "SULLIVAN ENVIRONMENTAL SERVICES INC.": "Environmental services",
  "SUPERIOR CONSTRUCTION COMPANY": "Construction",
  "Securing Florida's Future": "Political committee",
  "TAMPA BAY ENTERTAINMENT PROPERTIES LLC": "Real estate",
  "TEAM IP": "Promotional products",
  "TECO": "Energy utility",
  "TECO HOLDINGS INC.": "Energy utility",
  "TENET HEALTH": "Healthcare",
  "THE FUND": "Law firm",
  "THE GEO GROUP, INC.": "Private prisons",
  "THE MAIN LAW FIRM PL": "Law firm",
  "THE SEMINOLE TRIBE OF FLORIDA": "Gaming",
  "THE SOUTHERN GROUP PC": "Lobbying",
  "TL MANAGEMENT LLC": "Nursing homes",
  "TOWER HILL INSURANCE GROUP, LLC": "Property insurance",
  "TRI COUNTY DEVELOPMENT INC": "Developer",
  "TRULIEVE INC.": "Cannabis",
  "TURNBULL AND ASSOCIATES RUBIN": "Accounting",
  "Taxpayers for Better Schools": "Education",
  "The Vestcor Companies, Inc.": "Developer",
  "Truist Bank": "Banking",
  "U.S. CHAMBER OF COMMERCE AND RELATED ENTITIES": "Trade association",
  "UNITED GROUP UNDERWRITERS": "Property insurance",
  "UNITED STATES SUGAR CORPORATION": "Sugar",
  "UNIVERSAL CITY DEVELOPMENT PARTNERS GOVERNMENT RELATIONS": "Theme parks",
  "US SUGAR": "Sugar",
  "VALUES FIRST": "Political committee",
  "VENTURA SERVICES FLORIDA, LLC": "Nursing homes",
  "VITAS HEALTHCARE": "Healthcare",
  "W CENTRAL FLA CHAMBER ALLIANCE": "Trade association",
  "WALT DISNEY PARKS AND RESORTS": "Theme parks",
  "WALT DISNEY WORLD": "Theme parks",
  "WERNER, HOFFMAN, GREIG & GARCIA": "Law firm",
  "WEST FLORIDA OPTOMETRIC ASSOCIATION": "Trade association",
  "ZILLOW, INC": "Real estate tech",
  "bestbet Holdings, Inc.": "Gaming",
};

/**
 * The general-purpose engine: a filer's self-reported occupation, normalized
 * (trimmed, uppercased), mapped to a short industry label. This is what makes
 * the classifier apply to any entity, not just the ones reviewed by hand.
 */
export const OCCUPATION_MAP: Record<string, string> = {
  "501(C)(4) CIVIC LEAGUE": "Trade association",
  "ACHIEVA CREDIT UNION": "Credit unions",
  "ACUPUNCTURIST": "Healthcare",
  "ADDICTION TREATMENT CENTER": "Healthcare",
  "ADMINISTRATOR": "Consulting",
  "ADVERTISING": "Media/advertising",
  "ADVERTISING AGENCY": "Media/advertising",
  "AGRI-BUSINESS": "Agriculture",
  "AGRICULTURAL": "Agriculture",
  "AGRICULTURAL MARKETING": "Agriculture",
  "AGRICULTURE": "Agriculture",
  "AGRICULTURE EXECUTIVE": "Agriculture",
  "AIRCRAFT MANUFACTURER": "Aviation",
  "AIRPORT AVIATION": "Aviation",
  "ALF": "Nursing homes",
  "ALIVE CREDIT UNION": "Credit unions",
  "ANESTHESIOLOGIST": "Physician",
  "ANIMAL RETAIL STORE": "Retail",
  "APARTMENT ASSOCIATION": "Trade association",
  "APRN": "Healthcare",
  "AQUATIC AGRICULTURE": "Environmental services",
  "AQUATIC RESTORATION": "Environmental services",
  "ARCHITECHT": "Architecture",
  "ARCHITECT": "Architecture",
  "ARCHITECTURE": "Architecture",
  "AREA PRESIDENT  WASTE CO": "Waste management",
  "ARNP": "Healthcare",
  "ART CONSERVATOR": "Entertainment",
  "ASPHALT": "Construction",
  "ASPHALT PAVING": "Construction",
  "ASSET MANAGEMENT": "Investments",
  "ASSOCIATION": "Trade association",
  "ATHLETIC VENUE": "Professional sports",
  "ATT": "Law firm",
  "ATTORNEY": "Law firm",
  "ATTORNEY OFFICE": "Law firm",
  "ATTORNEYS": "Law firm",
  "ATTORNEYS AT LAW": "Law firm",
  "ATTY": "Law firm",
  "AUTO DEALER": "Auto dealers",
  "AUTO DEALERSHIP": "Auto dealers",
  "AUTO DEALERSHIP EXECUTIVE": "Auto dealers",
  "AUTO REPAIR": "Auto repair",
  "AUTO REPAIR SHOP OWNER": "Auto repair",
  "AUTO SALES": "Auto dealers",
  "AUTOMOBILE DEALER": "Auto dealers",
  "AUTOMOTIVE": "Auto dealers",
  "AUTOMOTIVE COMPANY": "Auto dealers",
  "AUTOMOTIVE DEALER": "Auto dealers",
  "AUTOMOTIVE REPAIR": "Auto repair",
  "AUTOMOTIVE RETAIL": "Auto dealers",
  "AUTOMOTIVE SALES": "Auto dealers",
  "AUTOMOTIVE SERVICES": "Auto repair",
  "AUTOMOTIVES": "Auto dealers",
  "AVIATION": "Aviation",
  "BAIL BONDS": "Corrections",
  "BANK": "Banking",
  "BANKER": "Financial services",
  "BANKING": "Banking",
  "BASEBALL TEAM": "Professional sports",
  "BEER DISTRIBUTOR": "Alcohol",
  "BEHAVIORAL COUNSELING CO.": "Healthcare",
  "BEVERAGE ASSOCIATION": "Trade association",
  "BEVERAGE COMPANY": "Alcohol",
  "BEVERAGE DISTRIBUTION": "Alcohol",
  "BEVERAGE DISTRIBUTION COMPANY": "Alcohol",
  "BEVERAGE DISTRIBUTOR": "Alcohol",
  "BIOPHARMACEUTICAL COMPANY": "Pharmaceuticals",
  "BIOTECHNOLOGY": "Pharmaceuticals",
  "BIOTECHNOLOGY COMPANY": "Pharmaceuticals",
  "BO/WHOLESALE NURSERY": "Agriculture",
  "BOAT MANUFACTURING": "Manufacturing",
  "BRAND AMBASSADOR": "Media/advertising",
  "BROKER TRADER": "Financial services",
  "BUILDER": "Developer",
  "BUILDER/CONTRACTOR": "Developer",
  "BUILDER/DEVELOPER": "Developer",
  "BUILDING INDUSTRY": "Developer",
  "BUILDING SUPPLIES": "Construction",
  "BUSINESS": "Consulting",
  "BUSINESS CONSULTANT": "Consulting",
  "BUSINESS CONSULTING": "Consulting",
  "BUSINESS DEVELOPMENT": "Technology",
  "BUSINESS EXECUTIVE": "Consulting",
  "BUSINESS IDENTITY": "Retail",
  "BUSINESS OPERATIONS - CONSULTA": "Consulting",
  "BUSINESS OWNER / SELF EMPLOYED": "Consulting",
  "BUSINESS STRATEGIST": "Consulting",
  "BUSINESS TECHNOLOGY": "Technology",
  "CAMPAIGN": "Candidate committee",
  "CAMPAIGN ACCOUNT": "Candidate committee",
  "CAMPGROUND": "Campgrounds",
  "CANDIDATE": "Candidate committee",
  "CANDIDATE CAMPAIGN": "Candidate committee",
  "CANDIDATE CAMPAIGN/DISPOSITION": "Candidate committee",
  "CANDIDATE COMMITTEE": "Candidate committee",
  "CAR DEALER": "Auto dealers",
  "CAR DEALERSHIP": "Auto dealers",
  "CAR DEALERSHIP OWNER": "Auto dealers",
  "CAR WASH": "Transportation",
  "CARD SERVICES": "Financial services",
  "CAREER & TECH EDUCATION": "Education",
  "CARPENTRY": "Construction",
  "CARRYOVER FUNDS FROM PREVIOUS": "Candidate committee",
  "CASINO": "Gaming",
  "CASINO GAMING": "Gaming",
  "CATTLE RANCH": "Agriculture",
  "CBD PRODUCTS": "Hemp products",
  "CELLULOSE PRODUCT MANUFACTURE": "Manufacturing",
  "CEO": "Consulting",
  "CEO ADVANCED ROOFING INC": "Roofing",
  "CERTIFIED PLANNER": "Engineering",
  "CFO/CONTROLLER/CHIEF ACCOUNTAN": "Consulting",
  "CFP": "Financial services",
  "CHAIRMAN/HANLEY FOUNDATION": "Trade association",
  "CHEMICAL COMPANY": "Manufacturing",
  "CHEMICAL MANUFACTURING CO.": "Manufacturing",
  "CHEMICAL MANUFACTURING SALES": "Manufacturing",
  "CHEMICAL SUPPLY COMPANY": "Manufacturing",
  "CHILD CARE PROVIDER": "Healthcare",
  "CHILD WELFARE FIRM": "Healthcare",
  "CHILDCARE PROVIDERS": "Healthcare",
  "CHILDREN'S BAHAVIORAL HEALTH": "Healthcare",
  "CHIROPRACTOR": "Healthcare",
  "CITY COUNTY EMPLOYEES CREDIT U": "Credit unions",
  "CIVIL ENGINEER": "Engineering",
  "CIVIL ENGINEER FIRM": "Engineering",
  "CIVIL ENGINEERING": "Engineering",
  "CLINIC": "Healthcare",
  "CNA": "Healthcare",
  "COFFEE SHOP": "Restaurants",
  "COMMERCIAL LANDSCAPE MANAGEMEN": "Construction",
  "COMMERCIAL REAL ESTATE": "Real estate",
  "COMMERCIAL SATELLITES": "Technology",
  "COMMUNICATIONS": "Telecom",
  "COMMUNICATIONS EXECUTIVE": "Telecom",
  "COMMUNICATIONS SERVICE PROVIDE": "Telecom",
  "COMMUNITY DEVELOPMENT ASSOCIAT": "Trade association",
  "COMMUNITY SOUTH CREDIT UNION": "Credit unions",
  "COMPOSTING MANAGEMENT": "Waste management",
  "CONGRESSIONAL CANDIDATE CAMPAI": "Candidate committee",
  "CONNECT CREDIT UNION": "Credit unions",
  "CONSTRUCTION": "Construction",
  "CONSTRUCTION AGGREGATES CEO": "Construction",
  "CONSTRUCTION COMPANY": "Construction",
  "CONSTRUCTION COMPANY CEO": "Construction",
  "CONSTRUCTION CONTRACTOR": "Construction",
  "CONSTRUCTION DEVELOPMENT": "Developer",
  "CONSTRUCTION EQUIPMENT": "Construction",
  "CONSTRUCTION EQUIPMENT COMPANY": "Manufacturing",
  "CONSTRUCTION INDUSTRY": "Construction",
  "CONSTRUCTION MANAGEMENT CO.": "Construction",
  "CONSTRUCTION MANAGER": "Construction",
  "CONSTRUCTION SERVICES": "Construction",
  "CONSTRUCTION TRADE ASSOC": "Trade association",
  "CONSULTANT": "Consulting",
  "CONSULTING": "Consulting",
  "CONSULTING & ENGINEERING": "Engineering",
  "CONSULTING FIRM": "Consulting",
  "CONSUMER MARKETING FIRM": "Media/advertising",
  "CONTRACTOR": "Construction",
  "CONTRACTORS": "Construction",
  "CONTROLLER": "Consulting",
  "CORPORATE DEVELOPMENT": "Technology",
  "CORRECTIONAL FACILITY": "Private prisons",
  "COUNTRY CLUB": "Hospitality",
  "COURT REPORTING": "Legal services",
  "CPA": "Accounting",
  "CRANE ASSOCIATION": "Trade association",
  "CREDIT CARD PROCESSING": "Financial services",
  "CRNA": "Healthcare",
  "CUSTOM CABINETRY": "Construction",
  "CUSTOM HOME BUILDER": "Developer",
  "DEPOSIT TO POLITICAL COMMITTEE": "Candidate committee",
  "DERMATOLOGIST": "Physician",
  "DERMATOLOGIST CEO": "Physician",
  "DERMATOLOGY PHYSICIAN": "Physician",
  "DESSERT SHOP": "Restaurants",
  "DEVELOPER": "Developer",
  "DEVELOPMENT": "Developer",
  "DEVELOPMENT MANAGEMENT": "Developer",
  "DIGITAL INTELLIGENCE": "Technology",
  "DIGITAL MARKETING": "Media/advertising",
  "DISABLED": "Disabled",
  "DISASTER RECOVERY CO.": "Environmental services",
  "DISTRIBUTION CENTER": "Logistics",
  "DISTRIBUTOR": "Retail",
  "DISTRIBUTORS": "Retail",
  "DISTRUBTOR": "Retail",
  "DOCTOR": "Physician",
  "DREDGING COMPANY": "Construction",
  "ECOLOGICAL CONSULTING": "Environmental services",
  "ECOLOGICAL CONSULTING CO.": "Environmental services",
  "ECOLOGICAL RESTORATION": "Environmental services",
  "ECOLOGICAL RESTORATION CO.": "Environmental services",
  "ECONOMIC DEVELOPMENT": "Consulting",
  "EDUCATION": "Education",
  "EDUCATION ASSOCIATION": "Trade association",
  "EDUCATION CONSULTANT": "Education",
  "EDUCATION DEVELOPMENT": "Education",
  "EDUCATION EXECUTIVE": "Education",
  "EDUCATION MANAGEMENT": "Education",
  "EDUCATION TECHNOLOGY": "Technology",
  "EDUCATION TECHNOLOGY CO.": "Technology",
  "EDUCATION TECHNOLOGY COMPANY": "Technology",
  "EDUCATIONAL": "Education",
  "EDUCATIONAL SERVICES": "Education",
  "EDUCATOR": "Education",
  "EINGINEERING": "Engineering",
  "ELECTED OFFICIAL": "Elected official",
  "ELECTRCIAN SERVICES": "Construction",
  "ELECTRIC COMPANY": "Energy utility",
  "ELECTRIC MOTOR REPAIR COMPANY": "Auto repair",
  "ELECTRICAL CONTRACTING": "Construction",
  "ELECTRICAL CONTRACTING CO": "Construction",
  "ELECTRICAL CONTRACTOR": "Construction",
  "ELECTRICIAN": "Construction",
  "EMERGENCY MANAGEMENT": "Emergency medical services",
  "ENERGY COMPANY": "Energy utility",
  "ENERGY CORPORATION": "Energy utility",
  "ENGINEER": "Engineering",
  "ENGINEERING": "Engineering",
  "ENGINEERING CONSULTANT": "Engineering",
  "ENGINEERING CONSULTING": "Engineering",
  "ENGINEERING CONSULTING FIRM": "Engineering",
  "ENGINEERING FIRM": "Engineering",
  "ENGINEERING/PROJECT MANAGEMENT": "Engineering",
  "ENTERTAINMENT": "Entertainment",
  "ENTERTAINMENT COMPANY": "Entertainment",
  "ENTERTAINMENT MANUFACTURER": "Entertainment",
  "ENTREPRENEUR": "Consulting",
  "ENVIROMENTAL CONSULTANT": "Environmental services",
  "EQUIPMENT RENTAL": "Manufacturing",
  "EQUIPMENT RENTALS": "Manufacturing",
  "ESTATES": "Real estate",
  "EVENTS MANAGEMENT": "Consulting",
  "EXCAVATING CONTRACTOR CO.": "Construction",
  "EXEC PACKAGING MACHINERY": "Manufacturing",
  "EXECUTIVE": "Consulting",
  "EXECUTIVE COUNCIL ASSISTANT": "Consulting",
  "FAIRWINDS CREDIT UNION": "Credit unions",
  "FAMILY OFFICE INVESTMENT MANAG": "Private equity",
  "FARM": "Agriculture",
  "FARMER": "Agriculture",
  "FARMER - HAMILLS HACIENDA, LLC": "Agriculture",
  "FARMER, RANCHER": "Agriculture",
  "FENCE CONTRACTING": "Construction",
  "FERTILIZER MANUFACTURER": "Manufacturing",
  "FINANCE": "Financial services",
  "FINANCE AND INSURANCE": "Insurance",
  "FINANCIAL": "Financial services",
  "FINANCIAL ADVISOR": "Financial services",
  "FINANCIAL CONSULTANT": "Financial services",
  "FINANCIAL CONSULTING FIRM": "Financial services",
  "FINANCIAL EXCHANGE COMPANY": "Financial services",
  "FINANCIAL HOLDINGS": "Investments",
  "FINANCIAL INVESTING": "Investments",
  "FINANCIAL INVESTMENTS": "Investments",
  "FINANCIAL INVESTOR": "Investments",
  "FINANCIAL LENDING SERVICES": "Financial services",
  "FINANCIAL SERVICES": "Financial services",
  "FINANCIAL SERVICES CO. EXEC.": "Technology",
  "FINANCIAL TECHNOLOGY COMPANY": "Financial services",
  "FINANCIALS SERVICES": "Financial services",
  "FIRE FIGHTERS UNION": "Labor union",
  "FIRE PROTECTION": "Construction",
  "FIRE PROTECTION SERVICES": "Construction",
  "FIRE SPRINKLER INSTALLERS": "Construction",
  "FIRE SPRINKLER SYSTEMS": "Construction",
  "FIREFIGHTER": "Firefighters",
  "FIREFIGHTER UNION": "Labor union",
  "FIREFIGHTERS": "Firefighters",
  "FIRST COMMERCE CREDIT UNION": "Credit unions",
  "FL STATE SENATOR": "Elected official",
  "FLIGHT ACADEMY TRAINER": "Aviation",
  "FLORIST": "Retail",
  "FLUID HANDLING PRODUCTS CO": "Manufacturing",
  "FOOD & BEVERAGE": "Restaurants",
  "FOOD & BEVERAGE DISTRIBUTION": "Restaurants",
  "FOOD AND BEVERAGE PROVIDER": "Restaurants",
  "FOOD AND HOSPITALITY SERVICES": "Restaurants",
  "FOOD DISTRIBUTION": "Restaurants",
  "FOOD SERVICE": "Restaurants",
  "FOOD SERVICE INDUSTRY": "Restaurants",
  "FOOTBALL COACH": "Professional sports",
  "FORENSICS": "Technology",
  "FOREST EQUIPMENT SUPPLIER": "Manufacturing",
  "FORESTRY": "Timber",
  "FORESTRY AND AGRICULTURAL": "Timber",
  "FOUNDATION EXECUTIVE": "Trade association",
  "FREIGHT FORWARDING COMPANY": "Logistics",
  "FREIGHT INTELLIGENCE": "Logistics",
  "FRIEND OF FORESTRY": "Timber",
  "FRLA MEMBER": "Trade association",
  "FRLA PRESIDENT": "Trade association",
  "FUEL": "Petroleum",
  "GAMING": "Gaming",
  "GAS CONTRACTOR": "Construction",
  "GENERAL & ROOFING CONTRACTOR": "Construction",
  "GENERAL CONTRACTING": "Construction",
  "GENERAL CONTRACTOR": "Construction",
  "GENERAL CONTRACTOR CEO": "Construction",
  "GEOTECH ENGINEERING": "Engineering",
  "GLASS CONTRACTOR": "Construction",
  "GLASS MANUFACTURING": "Manufacturing",
  "GLOBAL CRUISE CO": "Hospitality",
  "GM": "Auto dealers",
  "GOVERNMENT": "Elected official",
  "GOVERNMENT AFFAIRS": "Lobbying",
  "GOVERNMENT AGENCY": "Elected official",
  "GOVERNMENT CONSULTANT": "Lobbying",
  "GOVERNMENT CONSULTING": "Lobbying",
  "GOVERNMENT RELATIONS": "Lobbying",
  "GOVERNMENT RELATIONS FIRM": "Lobbying",
  "GOVERNMENTAL AFFAIRS": "Lobbying",
  "GOVERNMENTAL CONSULTANT": "Lobbying",
  "GOVERNMENTAL CONSULTING": "Lobbying",
  "GOVERNMENTAL RELATIONS": "Lobbying",
  "GOVT RELATIONS": "Lobbying",
  "GOVT. RELATIONS": "Lobbying",
  "GREEN HOUSE BLDG.": "Agriculture",
  "GROCERY": "Restaurants",
  "GULF WINDS CREDIT UNION": "Credit unions",
  "HEALTH & WELLNESS COMPANY": "Healthcare",
  "HEALTH ARE EXECUTIVE": "Healthcare",
  "HEALTH CARE": "Healthcare",
  "HEALTH CARE & HOSPITALS": "Healthcare",
  "HEALTH CARE ASSOCIATION": "Healthcare",
  "HEALTH CARE COMPANY": "Healthcare",
  "HEALTH CARE EXECUTIVE": "Healthcare",
  "HEALTH CARE FINANCIAL EXECUTIV": "Healthcare",
  "HEALTH CARE SERVICES": "Healthcare",
  "HEALTH CARE TECHNOLOGY EXECUTI": "Healthcare",
  "HEALTH INS. CO.": "Health insurance",
  "HEALTH INSURANCE": "Health insurance",
  "HEALTH INSURANCE AGENCY": "Health insurance",
  "HEALTH SUPPLY CHAIN": "Technology",
  "HEALTHCARE": "Healthcare",
  "HEALTHCARE ADMINISTRATOR": "Healthcare",
  "HEALTHCARE EXECUTIVE": "Healthcare",
  "HEALTHCARE MARKETING & COMMUNI": "Healthcare",
  "HEALTHCARE ORGANIZATION": "Healthcare",
  "HEALTHCARE REAL ESTATE DEVELOP": "Developer",
  "HEALTHCARE SERVICES": "Healthcare",
  "HEALTHCARE TECHNOLOGY": "Technology",
  "HEARING TECHNOLOGY": "Technology",
  "HEAVY EQUIPMENT": "Manufacturing",
  "HELATHCARE": "Healthcare",
  "HEMP WHOLESALER": "Hemp products",
  "HOLDING COMPANY": "Investments",
  "HOME BUILDER": "Developer",
  "HOME CONSTRUCTION": "Developer",
  "HOME HEALTH AGENCY": "Healthcare",
  "HOME HEALTH CARE": "Healthcare",
  "HOME LOANS": "Financial services",
  "HOME MAKER": "Homemaker",
  "HOME MORTGAGE LENDER": "Financial services",
  "HOMEBUILDER": "Developer",
  "HOMEBUILDERS ASSOCIATION": "Developer",
  "HOMEMAKER": "Homemaker",
  "HOMEOWNER'S INSURANCE": "Property insurance",
  "HORIZONTAL SITE AND UTILITY DE": "Construction",
  "HORSE BREEDER": "Horse breeding",
  "HOSPITAL": "Healthcare",
  "HOSPITALITY": "Hospitality",
  "HOTEL": "Hospitality",
  "HOTEL HOSPITALITY": "Hospitality",
  "HOUSE WIFE": "Homemaker",
  "HOUSEWIFE": "Homemaker",
  "HOUSING": "Developer",
  "HOUSING DEVELOP": "Developer",
  "HOUSING DEVELOPER": "Developer",
  "HOUSING DEVELOPMENT CHAIRMAN &": "Developer",
  "HOUSING DEVELOPMENT CHAIRMAN&": "Developer",
  "HOUSING INDUSTRY": "Developer",
  "HUMAN SERVICES CONSULTANT": "Consulting",
  "HURRICANE PROTECTION SOLUTIONS": "Construction",
  "HVAC CONTRACTOR": "Construction",
  "HVAC SERVICES": "Construction",
  "HYDRAULIC REPAIR": "Manufacturing",
  "INDUSTRIAL EQUIPMENT COMPANY": "Manufacturing",
  "INDUSTRIAL EQUIPMENT SUPPLY": "Manufacturing",
  "INDUSTRY CONFERENCE": "Trade association",
  "INFORMATION SERVICES": "Technology",
  "INFORMATION TECHNOLOGIST": "Technology",
  "INFORMATION TECHNOLOGY": "Technology",
  "INFRASTRUCTURE": "Infrastructure",
  "INSURANCE": "Insurance",
  "INSURANCE ADVISOR": "Insurance",
  "INSURANCE AGENT": "Insurance",
  "INSURANCE COMPANY": "Insurance",
  "INSURANCE EXECUTIVE": "Insurance",
  "INSURANCE SALES": "Insurance",
  "INTELLIGENCE/DEFENSE CONSULTIN": "Lobbying",
  "INTERIOR DESIGNER": "Architecture",
  "INTERNATIONAL ART FAIR COMPANY": "Entertainment",
  "INTERNET COMMERCE": "Technology",
  "INTERNET SERVICES": "Technology",
  "INVESTING": "Investments",
  "INVESTMENT ADVISORS": "Investments",
  "INVESTMENT EXECUTIVE": "Investments",
  "INVESTMENT HOLDING COMPANY": "Investments",
  "INVESTMENT MANAGEMENT": "Investments",
  "INVESTMENT SERVICES": "Investments",
  "INVESTMENTS": "Investments",
  "INVESTOR": "Investments",
  "IRONWORKER": "Construction",
  "IRRIGATION": "Construction",
  "IT": "Technology",
  "JOB TRAINING": "Education",
  "JSO": "Law enforcement",
  "KENNEL CLUB": "Greyhound racing",
  "LABOR UNION": "Labor union",
  "LABORATORY": "Laboratory services",
  "LAND DEVELOPER": "Developer",
  "LAND DEVELOPMENT": "Developer",
  "LAND INVESTMENT COMPANY": "Real estate",
  "LAND MANAGEMENT": "Real estate",
  "LAND OWNER": "Real estate",
  "LAND PLANNER": "Engineering",
  "LAND SERVICES": "Real estate",
  "LAND SURVEYING": "Engineering",
  "LAND SURVEYOR": "Engineering",
  "LANDOWNER": "Real estate",
  "LANDSCAPE ARCHITECT": "Construction",
  "LANDSCAPE SUPPLY": "Construction",
  "LANDSCAPING": "Construction",
  "LANDSCAPING COMPANY": "Construction",
  "LAW ENFORCEMENT": "Law enforcement",
  "LAW ENFORCEMENT - SHERIFF": "Law enforcement",
  "LAW ENFORCEMENT OFFICER": "Law enforcement",
  "LAW FIRM": "Law firm",
  "LAW GROUP": "Law firm",
  "LAW OFFICE": "Law firm",
  "LAWFIRM": "Law firm",
  "LAWN MAINTENANCE BUSINESS": "Construction",
  "LAWYER": "Law firm",
  "LCSW": "Healthcare",
  "LEGAL ASSISTANT": "Law firm",
  "LEGAL MARKETING": "Law firm",
  "LEGAL SERVICES": "Law firm",
  "LEO": "Law enforcement",
  "LICENSE PLATE MANUFACTURER": "Manufacturing",
  "LIFE INSURANCE": "Insurance",
  "LIFESAVING EQUIPMENT MANUFACTU": "Manufacturing",
  "LIGHTING TECHNOLOGY": "Technology",
  "LIMESTONE QUARRY": "Mining",
  "LIVESTOCK RANCHING": "Agriculture",
  "LMT": "Healthcare",
  "LOBBYING AND COMMUNICATIONS": "Lobbying",
  "LOBBYING FIRM": "Lobbying",
  "LOBBYIST": "Lobbying",
  "LOCAL HOME BUILDERS ASSOC.": "Developer",
  "LODGE": "Hospitality",
  "LODGING": "Hospitality",
  "LOGISTICS": "Logistics",
  "LOGISTICS MANAGEMENT": "Logistics",
  "LPN": "Healthcare",
  "MANAGEMENT COMPANY": "Property management",
  "MANAGEMENT CONSULTING": "Consulting",
  "MANAGEMENT SOLUTIONS": "Technology",
  "MANAGING DIRECTOR": "Technology",
  "MANUFACTURED HOUSING": "Manufactured housing",
  "MANUFACTURING": "Manufacturing",
  "MARIJUANA DISPENSARY & PRODUCT": "Cannabis",
  "MARINA": "Hospitality",
  "MARINE MANUFACTURING": "Manufacturing",
  "MARKETING": "Media/advertising",
  "MARKETING DIRECTOR": "Media/advertising",
  "MD": "Physician",
  "MECHANICAL CONTRACTING COMPANY": "Construction",
  "MEDIA": "Media/advertising",
  "MEDIA BROADCASTING": "Media/advertising",
  "MEDIA ENTERTAINMENT": "Media/advertising",
  "MEDIA PRODUCTION": "Media/advertising",
  "MEDIA/DIGITAL SERVICES": "Media/advertising",
  "MEDICAL DISPENSARY": "Cannabis",
  "MEDICAL DOCTOR": "Physician",
  "MEDICAL DRUG COMPANY": "Pharmaceuticals",
  "MEDICAL PROFESSIONAL": "Healthcare",
  "MEDICAL SERVICE AND HEALTH INS": "Healthcare",
  "MEDICAL STAFF": "Healthcare",
  "MEDICAL TECHNOLOGY": "Pharmaceuticals",
  "MEDICAL TRANSPORT": "Transportation",
  "MEDICAL TRANSPORTATION": "Healthcare",
  "MEMBERSHIP ASSOCIATION": "Trade association",
  "MENTAL HEALTH": "Healthcare",
  "MERCHANDISE DISTRIBUTOR": "Retail",
  "METAL SALES & RECYCLING": "Waste management",
  "METAL SUPPLIER": "Manufacturing",
  "MIAMI BEACH CITY COMMISSIONER": "Elected official",
  "MID FLORIDA CU": "Credit unions",
  "MINISTER": "Clergy",
  "MOBILE GAMING KIOSKS": "Gaming",
  "MOBILITY EQUIPMENT SUPPLIES": "Rideshare",
  "MONITORING SOLUTIONS": "Technology",
  "MORGAGE LEND SERVICE": "Financial services",
  "MORTGAGE": "Financial services",
  "MORTGAGE BROKER": "Financial services",
  "MORTGAGE LENDER": "Financial services",
  "MORTGAGE LENDING COMPANY": "Financial services",
  "MORTGAGE PROFESSIONAL": "Financial services",
  "MORTGAGE TRADE ASSOCITION": "Trade association",
  "MUSIC TEACHER": "Entertainment",
  "NATIONAL REAL EST TRADE ASSN.": "Trade association",
  "NATIONAL TRADE ASSOCIATION": "Trade association",
  "NATIVE AMERICAN TRIB": "Native American gaming",
  "NATURAL GAS DISTRIBUTOR": "Energy utility",
  "NATURAL GAS PROVIDER": "Energy utility",
  "NATURAL GAS SUPPLIER": "Energy utility",
  "NAVY PILOT": "Aviation",
  "NEFBA": "Developer",
  "NON-PROFIT": "Trade association",
  "NON-PROFIT CEO": "Trade association",
  "NON-PROFIT EXECUTIVE": "Trade association",
  "NOT EMPLOYED": "Unemployed",
  "NOT FOR PROFIT CORPORATION": "Trade association",
  "NOT WORKING": "Unemployed",
  "NOT-EMPLOYED": "Unemployed",
  "NP": "Healthcare",
  "NTRA": "Horse racing",
  "NURSE": "Healthcare",
  "NURSERY OWNER/GROWER": "Agriculture",
  "NURSING HOME": "Nursing homes",
  "NURSING HOMES": "Nursing homes",
  "OFFICE MANAGER": "Consulting",
  "ONLINE RETAIL": "Retail",
  "ONLINE RETAILER": "Retail",
  "ONLINE SOFTWARE SOLUTIONS": "Technology",
  "OPHTHALMOLOGIST": "Physician",
  "OPTHAMOLOGIST": "Physician",
  "OPTOMETRIC ASSOC/NPO-C3": "Trade association",
  "OPTOMETRIST": "Healthcare",
  "ORGANIC BUSINESS": "Healthcare",
  "ORTHOPEDIC": "Physician",
  "ORTHOPEDICS": "Physician",
  "OSTEOPATHIC PHYSICIAN": "Physician",
  "OUTDOOR ADVERTISING": "Media/advertising",
  "OWNER": "Consulting",
  "PA": "Healthcare",
  "PAC": "Political committee",
  "PACK AND SHIPPING CO.": "Logistics",
  "PAINTING": "Construction",
  "PARI MUTUEL": "Horse racing",
  "PARI-MUTUEL": "Horse racing",
  "PARIMUTUEL": "Horse racing",
  "PARK MANAGEMENT": "Property management",
  "PARTNER": "Consulting",
  "PATHOLOGY": "Physician",
  "PAVING SERVICES": "Construction",
  "PAWNBROKERS": "Retail",
  "PC": "Political committee",
  "PC- BANKING": "Political committee",
  "PERSONAL PROTECTION": "Firearms",
  "PERSONAL TRAINER": "Fitness",
  "PEST CONTROL": "Pest control",
  "PETROLEUM": "Petroleum",
  "PETROLEUM BUSINESS COMPANY": "Petroleum",
  "PHARMACEUTICAL COMPANY": "Pharmaceuticals",
  "PHARMACEUTICALS": "Pharmaceuticals",
  "PHARMACIST": "Pharmaceuticals",
  "PHARMACY": "Pharmaceuticals",
  "PHARMUCETICAL MANFACTURER": "Pharmaceuticals",
  "PHOSPHATE COMPANY": "Phosphate mining",
  "PHOSPHATE RESEARCH COMPANY": "Phosphate mining",
  "PHOTO SPEED ENFORCEMENT TECH": "Transportation",
  "PHOTOGRAPHER": "Media/advertising",
  "PHYSICAL THERAPIST": "Healthcare",
  "PHYSICIAN": "Physician",
  "PIANO MUSICIAN": "Entertainment",
  "PILOT": "Aviation",
  "PIPE SERVICES": "Construction",
  "PLUMBING COMPANY": "Construction",
  "POLICE OFFICER": "Law enforcement",
  "POLITCAL COMMITTEE": "Political committee",
  "POLITICAL": "Political committee",
  "POLITICAL ACTION COMMITTEE": "Political committee",
  "POLITICAL CLUB": "Political committee",
  "POLITICAL COMMITTEE": "Political committee",
  "POLITICAL COMMITTEE (PC)": "Political committee",
  "POLITICAL CONSULTANT": "Lobbying",
  "POLITICAL CONSULTING": "Lobbying",
  "POLITICAL ORG.": "Political committee",
  "POLITICAL ORGANIZATION": "Political committee",
  "POLITICAL PARTY": "Political party",
  "POOL CONTRACTOR": "Construction",
  "POOL SERVICE COMPANY": "Construction",
  "PRACTICAL MANAGEMENT COMPANY": "Property management",
  "PRES/TODD MITCHELL ASSOC LLC": "Consulting",
  "PRESIDENT": "Consulting",
  "PRESIDENT - HERNANDO HOMEOWNER": "Trade association",
  "PRESIDENT AND FOUNDER - CONSUL": "Consulting",
  "PRESIDENT GLOBAL WATER": "Energy utility",
  "PRIVATE AVIATION SERVICES": "Aviation",
  "PRIVATE EQUITY": "Private equity",
  "PRIVATE EQUITY FIRM": "Private equity",
  "PRIVATE EQUITY INVESTOR": "Private equity",
  "PROCUREMENT": "Technology",
  "PRODUCER": "Media/advertising",
  "PROFESSIONAL ASSOCIATION": "Trade association",
  "PROFESSIONAL ATHLETICS": "Professional sports",
  "PROFESSIONAL DENTAL ASSOC": "Trade association",
  "PROFESSIONAL GOLFER": "Professional sports",
  "PROFESSOR": "Education",
  "PROMOTION CO/ADVERTISING": "Media/advertising",
  "PROMOTIONAL SUPPLIER": "Promotional products",
  "PROPERTY APPRAISER": "Real estate",
  "PROPERTY DEVELOPMENT": "Developer",
  "PROPERTY HOLDINGS": "Real estate",
  "PROPERTY INVESTOR": "Real estate",
  "PROPERTY MANAGEMENT": "Property management",
  "PROPERTY MANAGEMENT COMPANY": "Property management",
  "PROPERTY MANAGERS": "Property management",
  "PROPERTY RESTORATION": "Environmental services",
  "PROPERTY SALES": "Real estate",
  "PSYCHIATRIST": "Physician",
  "PUBLIC ADJUSTER": "Property insurance",
  "PUBLIC ADJUSTERS": "Property insurance",
  "PUBLIC AFFAIRS": "Lobbying",
  "PUBLIC AFFAIRS CONSULTING": "Lobbying",
  "PUBLIC AFFAIRS FIRM": "Lobbying",
  "PUBLIC RELATIONS": "Media/advertising",
  "PUBLIC SAFETY SOLUTIONS": "Cybersecurity",
  "R.E. DEVELOPERS": "Developer",
  "R.E. INVESTORS": "Real estate",
  "R.E. MANAGEMENT": "Real estate",
  "RAILROAD COMPANY": "Transportation",
  "RANCHER": "Agriculture",
  "RE DEVELOPMENT/INVESTMENTS": "Real estate",
  "REAL ESTATE": "Real estate",
  "REAL ESTATE AGENT": "Real estate",
  "REAL ESTATE BROKER": "Real estate",
  "REAL ESTATE COMPANY": "Real estate",
  "REAL ESTATE CONSTRUCTION": "Real estate",
  "REAL ESTATE CONSULTANT": "Real estate",
  "REAL ESTATE DEVELOMENT": "Developer",
  "REAL ESTATE DEVELOP": "Developer",
  "REAL ESTATE DEVELOPER": "Developer",
  "REAL ESTATE DEVELOPMENT": "Developer",
  "REAL ESTATE DEVELOPMENT CO.": "Developer",
  "REAL ESTATE HOLDING": "Real estate",
  "REAL ESTATE HOLDING CO.": "Real estate",
  "REAL ESTATE HOLDING CO. EXEC.": "Real estate",
  "REAL ESTATE HOLDING COMPANY": "Real estate",
  "REAL ESTATE HOLDINGS": "Real estate",
  "REAL ESTATE INVESTING": "Real estate",
  "REAL ESTATE INVESTMENT": "Real estate",
  "REAL ESTATE INVESTMENT CO.": "Real estate",
  "REAL ESTATE INVESTMENT COMPANY": "Real estate",
  "REAL ESTATE INVESTMENTS": "Real estate",
  "REAL ESTATE INVESTOR": "Real estate",
  "REAL ESTATE MANAGEMENT": "Real estate",
  "REAL ESTATE MANAGEMENT CO.": "Real estate",
  "REAL ESTATE MGR": "Real estate",
  "REALTOR": "Real estate",
  "REALTOR-": "Real estate",
  "REALTY": "Real estate",
  "RECRUITMENT EXECUTIVE": "Technology",
  "RECYCLING AND SOLID WASTE SERV": "Waste management",
  "RECYCLING ASSOCIATION": "Trade association",
  "REGISTERED AGENT": "Legal services",
  "REGISTERED NURSE": "Healthcare",
  "REHAB AND NURSING CENTER": "Healthcare",
  "RESIDENTIAL DEVELOPMENT": "Developer",
  "RESORT COALITION": "Trade association",
  "RESORT OWNER": "Hospitality",
  "RESTARUANT": "Restaurants",
  "RESTAURANT OWNER": "Restaurants",
  "RESTAURANTEUR": "Restaurants",
  "RESTAURATEUR": "Restaurants",
  "RESTORATION SERVICES": "Environmental services",
  "RET": "Retired",
  "RETAIL": "Retail",
  "RETAIL CHAIN": "Retail",
  "RETAIL GROCERY": "Restaurants",
  "RETAIL MANFACTURING": "Retail",
  "RETAIL SALES": "Retail",
  "RETAIL STORE": "Retail",
  "RETIRE": "Retired",
  "RETIRED": "Retired",
  "RETIRED-": "Retired",
  "RETIRED.": "Retired",
  "RETIREE": "Retired",
  "RETIREMENT COMMUNITY": "Healthcare",
  "RETRIED": "Retired",
  "RHEUMATOLOGIST": "Physician",
  "RHEUMATOLOGY PRACTICE": "Physician",
  "RN": "Healthcare",
  "ROAD CONSTRUCTION": "Construction",
  "ROAD CONTRACTOR": "Construction",
  "ROADWAY INFRASTRUCTURE": "Infrastructure",
  "ROOFING": "Roofing",
  "ROOFING ASSOCIATION": "Trade association",
  "RRNA": "Healthcare",
  "RUBBER PRODUCTS SUPPLY CO.": "Manufacturing",
  "RV PARK": "Campgrounds",
  "RV RESORT": "RV industry",
  "SALES & MARKETING": "Media/advertising",
  "SANITATION": "Waste management",
  "SCHOOL": "Education",
  "SCHOOL  REPRESENTATIVE": "Elected official",
  "SCHOOL SAFETY SOFTWARE CO.": "Technology",
  "SCRAP METAL RECYCLING FACILITY": "Waste management",
  "SECURITY CONSULTANT": "Technology",
  "SECURITY SYSTEMS": "Technology",
  "SELF": "Self-employed",
  "SELF EMPLOYED": "Self-employed",
  "SELF-EMPLOYED": "Self-employed",
  "SENIOR LIVING": "Healthcare",
  "SEPTIC SYSTEM SERVICES": "Construction",
  "SHERIFF": "Law enforcement",
  "SHIPPING SERVICES": "Logistics",
  "SITE CONSTRUCTION": "Construction",
  "SMART LIGHTING SOLUTIONS": "Technology",
  "SOCIAL MEDIA TECHNOLOGY": "Technology",
  "SOFTWARE": "Technology",
  "SOFTWARE COMPANY": "Technology",
  "SOFTWARE PUBLISHER": "Technology",
  "SOFTWARE SOLUTIONS": "Technology",
  "SOFTWARE TECHNOLOGY CO.": "Technology",
  "SPACE COAST CREDIT UNION": "Credit unions",
  "SPORTING CLUB": "Professional sports",
  "SPORTING GOODS": "Manufacturing",
  "SPORTS BAR ESTABLISHMENT": "Restaurants",
  "SPORTS BETTING": "Gaming",
  "SPORTS CLUB CHIEF OPERATING OF": "Professional sports",
  "SRNA": "Healthcare",
  "STAFFING EXECUTIVE": "Consulting",
  "STATE SENATOR": "Elected official",
  "STAY AT HOME MOM": "Homemaker",
  "STEEL FABRICATION": "Manufacturing",
  "STEEL MANUFACTURER": "Manufacturing",
  "STEM CELL": "Pharmaceuticals",
  "STONE SUPPLIER": "Manufacturing",
  "STORAGE ASSOCIATION": "Trade association",
  "STRATEGIC CONSULTING": "Consulting",
  "STRUCTURAL ENGINEERING COMPANY": "Engineering",
  "STRUCTURAL STEEL": "Construction",
  "STRUCTURED SETTLEMENTS": "Financial services",
  "STUDENT": "Education",
  "SUGEON": "Physician",
  "SUNCOAST CREDIT UNION": "Credit unions",
  "SUPERMARKET": "Restaurants",
  "SURETY BONDS": "Insurance",
  "SURGEON": "Physician",
  "SURVEYOR": "Engineering",
  "TAX CONSULTING": "Financial services",
  "TECH": "Technology",
  "TECH COMPANY CEO": "Technology",
  "TECHNOLOGY": "Technology",
  "TECHNOLOGY COMPANY": "Technology",
  "TECHNOLOGY CONSULTANT": "Technology",
  "TECHNOLOGY CONSULTING": "Technology",
  "TECHNOLOGY EXECUTIVE": "Technology",
  "TECHNOLOGY INVESTOR": "Venture capital",
  "TELECOMMUNICATIONS": "Telecom",
  "TELECOMMUNICATIONS CO.": "Telecom",
  "TELEPHONE": "Telecom",
  "TELEPHONE PROVIDER": "Telecom",
  "THERAPEUTICS": "Pharmaceuticals",
  "THERAPUETICS": "Pharmaceuticals",
  "THOROUGHBRED BREEDER & OWNER": "Horse breeding",
  "THOROUGHBRED BREEDER AND OWNER": "Horse breeding",
  "TIRE SHOP": "Auto repair",
  "TITLE COMPANY": "Title insurance",
  "TITLE SERVICES": "Title insurance",
  "TOBACCO": "Tobacco",
  "TOBACCO DISTRIBUTOR": "Tobacco",
  "TOBACCO PRODUCTS": "Tobacco",
  "TOWING": "Transportation",
  "TOWING SERVICE": "Transportation",
  "TOWING SERVICES": "Transportation",
  "TRADE ASSN.": "Trade association",
  "TRADE ASSOCIATION": "Trade association",
  "TRADE ASSOCIATION CHAPTER": "Trade association",
  "TRAFFIC SAFETY": "Transportation",
  "TRAFFIC SAFETY CAMERAS": "Transportation",
  "TRANSMISSIONS": "Auto repair",
  "TRANSORT COMPANY": "Trucking",
  "TRANSPORT COMPANY": "Trucking",
  "TRANSPORTATION": "Transportation",
  "TRANSPORTATION CONSULTANTS": "Transportation",
  "TRANSPORTATION SOLUTIONS": "Transportation",
  "TRAVEL AGENCY": "Hospitality",
  "TREATMENT CENTER": "Healthcare",
  "TRUCKING": "Trucking",
  "TRUCKING CO.": "Trucking",
  "TRUST": "Investments",
  "UNEMPLOYED": "Unemployed",
  "UNION": "Labor union",
  "UNIVERSITY PRESIDENT": "Education",
  "UTILITIES": "Energy utility",
  "UTILITY COMPANY": "Energy utility",
  "UTILITY CONTRACTOR": "Construction",
  "VALVE SUPPLY CO.": "Manufacturing",
  "VAPE PRODUCTS": "Tobacco",
  "VENICE COUNCIL": "Elected official",
  "VENTURE CAPITALIST": "Venture capital",
  "VP - ELECTRICAL CONTRACTING": "Construction",
  "VP AUTO DEALERSHIP": "Auto dealers",
  "VP GOVT AFFAIRS": "Lobbying",
  "VP OF MARKETING": "Media/advertising",
  "WARRANTY COMPANY": "Home warranty",
  "WASTE MANAGEMENT": "Waste management",
  "WASTE MANAGEMENT SVCS.": "Waste management",
  "WASTE SERVICES": "Waste management",
  "WATER & WASTE WORKER": "Energy utility",
  "WATER MANAGEMENT": "Energy utility",
  "WEALTH MANAGEMENT": "Financial services",
  "WEALTH MANAGEMENT FIRM": "Financial services",
  "WEB DESIGNER": "Technology",
  "WHOLESALE MORTGAGE LENDER": "Retail",
  "WHOLESALE/RETAIL PETRO EXECUTI": "Petroleum",
  "WHOLESALER": "Retail",
  "WINDOW CONTRACTOR": "Construction",
  "WINDOW MANUFACTURING": "Manufacturing",
};

/**
 * Second-tier fallback for occupations not in the exact map above — a
 * profession word that reliably names one industry regardless of what title
 * or modifier wraps around it ("RETIRED ATTORNEY", "ATTORNEY AT LAW", "SOLE
 * PRACTITIONER ATTORNEY" all resolve via one \bATTORNEY\b rule). Checked in
 * order, first match wins — more specific patterns are listed first so they
 * win over a broader one later (e.g. "SOFTWARE ENGINEER" -> Technology is
 * checked before the bare "ENGINEER" -> Engineering catch-all). Deliberately
 * excludes generic role words (Manager, Director, Sales, Counselor, Executive)
 * that span every industry -- sampled entity names behind the biggest of
 * those confirmed no common employer or sector.
 */
const OCCUPATION_KEYWORD_RULES: [RegExp, string][] = [
  [/\bSTATE FARM\b/i, "Insurance"],
  [/\b(SOFTWARE|WEB|COMPUTER|NETWORK|DATA|IT|SYSTEMS?)\s+(ENGINEER|DEVELOPER|PROGRAMMER|ANALYST|CONSULTANT)/i, "Technology"],
  [/\bPROGRAMMER\b|\bCOMPUTER PROGRAMMER\b/i, "Technology"],
  [/\bAIRCRAFT\s+MECHANIC\b|\bAIRPLANE\s+MECHANIC\b|\bAVIATION\s+MECHANIC\b|\bHELICOPTER\s+MECHANIC\b/i, "Aviation"],
  [/\bMEDICAL\b|\bDENTAL\b|\bDENTISTRY\b|\bCLINIC\b|\bNURS(E|ING)\b|\bHEALTH\s*CARE\b|\bHEALTHCARE\b/i, "Healthcare"],
  [/\bSPEECH[\s-]*(LANGUAGE)?\s*PATHOLOG/i, "Healthcare"],
  [/\bPHYSICIAN|\bSURGEON|\bSURGERY\b|\bOSTEOPATH|\bANESTHES|\bDERMATOLOG|\bOPHTHALMOLOG|\bOPTHAMOLOG|\bPSYCHIATR|\bRADIOLOG|\bCARDIOLOG|\bPEDIATRI|\bORTHOPEDIC|\bPATHOLOG|\bORAL SURGEON\b/i, "Physician"],
  [/\bDENTIST/i, "Healthcare"],
  [/\bTHERAP(Y|IST)\b|\bPSYCHOLOG|\bPSYCHOTHERAP|\bCOUNSELOR\b.*MENTAL|MENTAL.*\bCOUNSELOR\b/i, "Healthcare"],
  [/\bOPTICIAN\b|\bOPTOMETR|\bPODIATR/i, "Healthcare"],
  [/\bCHIROPRACT/i, "Healthcare"],
  [/\bDIETITIAN\b|\bNUTRITION/i, "Healthcare"],
  [/\bMIDWIFE\b|\bHYGIENIST\b|\bCAREGIVER\b|\bPARAMEDIC\b/i, "Healthcare"],
  [/\bSOCIAL WORK/i, "Healthcare"],
  [/\bACUPUNCTUR/i, "Healthcare"],
  [/\bPHARMAC/i, "Pharmaceuticals"],
  [/\bASSISTED LIVING\b|\bSENIOR LIVING\b|\bNURSING HOME/i, "Nursing homes"],
  [/\bEMERGENCY MED|\bAMBULANCE\b/i, "Emergency medical services"],
  [/\bVETERINAR/i, "Veterinary"],
  [/\bFIRE\s*FIGHT|\bFIREFIGHT|\bFIREMAN\b|\bFIRE\s+CHIEF\b/i, "Firefighters"],
  [/\bPOLICE\b|\bSHERIFF\b|\bLAW\s+ENFORCEMENT\b|\bDETECTIVE\b|\bCORRECTIONS?\s+OFFICER\b/i, "Law enforcement"],
  [/\bCORRECTIONAL\s+FACILITY\b/i, "Corrections"],
  [/\bJUDGE\b|\bCLERK\s+OF\s+COURT\b|\bTAX\s+COLLECTOR\b|\bCOMMISSIONER\b|\bLEGISLATOR\b|\bSTATE\s+REPRESENTATIVE\b|\bSTATE\s+SENATOR\b|\bMAYOR\b|\bSCHOOL\s+BOARD\s+MEMBER\b/i, "Elected official"],
  [/\bMILITARY\b|\bNAVY\b|\bARMY\b|\bAIR\s+FORCE\b|\bMARINE\s+CORPS\b|\bSOLDIER\b|\bNAVAL\s+OFFICER\b/i, "Military"],
  [/\bATTORNEY|\bLAWYER\b|\bPARALEGAL\b|\bLAW\s+(FIRM|CLERK|OFFICE|PROFESSOR)\b|\bLAW\b|\bLEGAL\b|\bPUBLIC DEFENDER\b|\bSTATE ATTORNEY\b/i, "Law firm"],
  [/\bLOBBY|\bGOVERNMENT RELATIONS\b|\bGOVERNMENTAL RELATIONS\b|\bGOVT\.?\s*RELATIONS\b|\bGOV(ERNMENT)?\s+AFFAIRS\b/i, "Lobbying"],
  [/\bMEDIATOR\b|\bARBITRAT/i, "Legal services"],
  [/\bTEACHER|\bEDUCATOR|\bPROFESSOR\b|\bLECTURER\b|\bLIBRARIAN\b|\bTUTOR\b|\bPRINCIPAL\b.*SCHOOL|SCHOOL.*\bPRINCIPAL\b|\bSUPERINTENDENT\b|\bFACULTY\b/i, "Education"],
  [/\bREAL\s*ESTATE\s*DEVELOP|\bLAND\s*DEVELOP|\bHOME\s*BUILD|\bRESIDENTIAL\s*DEVELOP|\bHOUSING\s*DEVELOP|\bDEVELOPER/i, "Developer"],
  [/\bPROPERTY\s+MANAG|\bAPARTMENT\s+(COMMUNITY|MANAG)/i, "Property management"],
  [/\bREAL\s*ESTATE|\bREALTOR\b|\bR\.?E\.?\s+(HOLDING|INVEST)|\bLANDLORD\b|\bHOME\s+INSPECT|\bSHOPPING\s+CENTER\b/i, "Real estate"],
  [/\bELECTRICIAN|\bELECTRICAL\s+CONTRACT/i, "Construction"],
  [/\bPLUMB/i, "Construction"],
  [/\bCARPENTER\b|\bCARPENTRY\b|\bPAINTER\b|\bPAINTING\s+CONTRACT|\bMASON\b|\bWELDER\b|\bLANDSCAP|\bPAVING\b|\bCONCRETE\b|\bSEPTIC\b|\bIRONWORKER\b|\bFIRE\s+SPRINKLER/i, "Construction"],
  [/\bBUILD(ER|ING\s+CONTRACT)|\bGENERAL\s+CONTRACT|\bCONSTRUCTION\b/i, "Construction"],
  [/\bROOF(ER|ING)\b/i, "Roofing"],
  [/\bARCHITECT/i, "Architecture"],
  [/\bINTERIOR\s+DESIGN/i, "Architecture"],
  [/\bSURVEYOR\b/i, "Engineering"],
  [/\bHAIR\s*(STYLIST|DRESSER)?\b|\bBARBER\b|\bCOSMETOLOG|\bESTHETICIAN\b|\bSALON\b|\bSTYLIST\b/i, "Personal care"],
  [/\bJOURNALIST\b|\bPUBLISH|\bEDITOR\b|\bPRINT(ER|ING)\b|\bPHOTOGRAPH|\bCOPYWRIT|\bTECHNICAL WRITER\b|\bFREELANCE WRITER\b|\bDIGITAL STRATEGIST\b|\bCREATIVE DIRECTOR\b/i, "Media/advertising"],
  [/\bMARKETING\b|\bMARKETER\b/i, "Media/advertising"],
  [/\bMUSICIAN\b|\bARTIST\b|\bACTOR\b|\bENTERTAINER\b|\bFILMMAKER\b|\bVIDEOGRAPHER\b/i, "Entertainment"],
  [/\bFINANC(E|IAL)\b|\bWEALTH\s+(ADVISOR|MANAG)|\bINVESTMENT\s+(BANKER|MANAGER|ADVISOR|FIRM)|\bMORTGAGE\s+(BANKER|LOAN)|\bLOAN\s+OFFICER\b|\bPORTFOLIO MANAGER\b|\bTRADER\b/i, "Financial services"],
  [/\bBANK(ER|ING)?\b/i, "Banking"],
  [/\bVENTURE\s*CAPITAL/i, "Venture capital"],
  [/\bACCOUNT(ANT|ING)\b|\bBOOKKEEP|\bAUDITOR\b|\bTAX\s+(PREPARER|ACCOUNTANT|CONSULTANT|COLLECTOR)\b/i, "Accounting"],
  [/\bINSURANCE\b|\bUNDERWRIT|\bCLAIMS?\s+ADJUST|\bINSURANCE\s+ADJUST/i, "Insurance"],
  [/\bLINE\s*TECHNICIAN|\bLINEMAN\b|\bELECTRIC\s+UTILITY\b|\bELECTRIC\s+COMPANY\b|\bUTILITY\s+CREW\b/i, "Energy utility"],
  [/\bSOLAR\b/i, "Energy utility"],
  [/\bPROPANE\b/i, "Petroleum"],
  [/\bENERGY\b/i, "Energy utility"],
  [/\bCITRUS\b/i, "Citrus"],
  [/\bTIMBER\b|\bLOGGER\b|\bFOREST(RY|ER)?\b|\bSILVICULTUR/i, "Timber"],
  [/\bRANCH|\bFARM(ER|ING)?\b|\bAGRIBUSINESS\b|\bAGRICULTUR/i, "Agriculture"],
  [/\bHORSE\s+(TRAINER|BREEDER)\b/i, "Horse breeding"],
  [/\bTRUCK(ING)?\s*(DRIVER|CO)?\b/i, "Trucking"],
  [/\bBUS\s+DRIVER\b|\bSCHOOL\s+BUS\b|\bDELIVERY\s+DRIVER\b|\bAIRLINE\s+PILOT\b/i, "Transportation"],
  [/\bBOAT\s+CAPTAIN\b|\bLONGSHOREMAN\b|\bHARBOR\s+PILOT\b|\bMARINE\s+SERVICES\b/i, "Logistics"],
  [/\bMECHANIC\b|\bAUTO\s*(MOTIVE)?\s+REPAIR\b/i, "Auto repair"],
  [/\bAUTO(MOBILE)?\s+DEALER|\bCAR\s+(SALES|DEALER)|\bMOTOR\s+VEHICLE\s+DEALER/i, "Auto dealers"],
  [/\bPILOT\b|\bFLIGHT\s+ATTENDANT\b/i, "Aviation"],
  [/\bRV\b/i, "RV industry"],
  [/\bPASTOR\b|\bMINISTE?R\b|\bCHAPLAIN\b|\bPRIEST\b|\bRABBI\b|\bCLERGY\b|\bCHURCH\b/i, "Clergy"],
  [/\bFUNERAL\b/i, "Funeral services"],
  [/\bENGINEER/i, "Engineering"],
  [/\bMACHINIST\b|\bMANUFACTUR/i, "Manufacturing"],
  [/\bCONSULT(ANT|ING)\b|\bMANAGEMENT CONSULT/i, "Consulting"],
  [/\bFITNESS\b|\bYOGA\b|\bPERSONAL TRAINER\b/i, "Fitness"],
  [/\bRESTAURANT|\bCHEF\b|\bBARTENDER\b|\bWAITRESS\b|\bBAKERY\b|\bCATERING\b/i, "Restaurants"],
  [/\bTITLE\s+(INSURANCE|AGEN)/i, "Title insurance"],
  [/\bTRADE\s+ASSOCIATION\b|\bPROFESSIONAL\s+ASSOCIATION\b/i, "Trade association"],
];

/**
 * Entities with no occupation on file whose *name* still names the industry —
 * a union's per-capita dues sweep ("18,588 MEMBERS @ $1.66"), a bundled
 * trade-event contribution sharing one amount across several exhibitors.
 */
const NAME_PATTERN_RULES: [RegExp, string][] = [
  [/MEMBERS\s*@\s*\$/i, "Labor union"],
  [/MUC'?S AT \$/i, "Labor union"],
  [/^\d+\s*@\s*\$/i, "Labor union"],
  [/CAMPAIGN( ACCOUNT)?$/i, "Candidate committee"],
  [/FLORIDA REPUBLICAN SENATORIAL/i, "Political party"],
  [/BEER WHOLESALERS/i, "Alcohol"],
  [/INJURY LAWYERS|ATTORNEYS AT LAW|\bP\.?A\.?$|\bLLP$/i, "Law firm"],
  [/WELLS FARGO BANK|SERVISFIRST BANK|^BANK OF |BANK$/i, "Banking"],
  [/PROPERTY MANAGEMENT/i, "Property management"],
  [/GROUNDED STRATEGIES/i, "Lobbying"],
];

/** A single bundled contribution (all rows share one amount, $760.14) from an RV-industry trade event. */
const RV_INDUSTRY_NAMES = new Set<string>([
  "BBMOTORHOMES, LLC",
  "FREEDOM MOBILE RV SERVICES",
  "KBS KREATIONS, LLC",
  "MANNY MOBILE REPAIRS, LLC",
  "SLINKY STOVE",
  "STEERING CREATIONS, INC.",
  "TALIN RV SERVICE",
  "TALLAHASSEE RV RENTAL",
  "TECHNORV/FOUNDRY BRANDS",
  "TRUE TEST RV REPAIR PARTS & STORAGE",
]);

/**
 * Classify one entity's industry/type.
 *
 * Checked in order: a known-entity override, the filed occupation, a name
 * pattern (dues sweeps, bundled contributions), then — only for committees,
 * parties and candidates, where the entity *is* its own type — a fallback on
 * `kind`. Returns null rather than guessing when nothing matches; a blank
 * column beats a confident-looking wrong one.
 */
export function classifyIndustry(
  occupation: string | null | undefined,
  name: string,
  kind?: string,
): string | null {
  const override = NAME_OVERRIDES[name];
  if (override) return override;

  const occ = (occupation ?? '').trim().toUpperCase();
  if (occ && occ !== 'N/A' && occ !== 'NA' && occ !== 'NONE') {
    const mapped = OCCUPATION_MAP[occ];
    if (mapped) return mapped;
    for (const [pattern, label] of OCCUPATION_KEYWORD_RULES) {
      if (pattern.test(occ)) return label;
    }
  }

  if (RV_INDUSTRY_NAMES.has(name)) return 'RV industry';
  for (const [pattern, label] of NAME_PATTERN_RULES) {
    if (pattern.test(name)) return label;
  }

  if (kind === 'candidate') return 'Candidate committee';
  if (kind === 'party') return 'Political party';
  if (kind === 'committee') return 'Political committee';

  return null;
}
